// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJJz44-o6_cMtmc2WHlX5bkWxCYfrmOgE',
    appId: '1:715990496723:web:d6f98b355c424e1386eb26',
    messagingSenderId: '715990496723',
    projectId: 'tonefix-app',
    authDomain: 'tonefix-app.firebaseapp.com',
    storageBucket: 'tonefix-app.firebasestorage.app',
    measurementId: 'G-7RG42PHY60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDJLOyvr7SUc9pXUVKSOqBpaH3kno8h80',
    appId: '1:715990496723:android:402691e2d49288a186eb26',
    messagingSenderId: '715990496723',
    projectId: 'tonefix-app',
    storageBucket: 'tonefix-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9NpIFsEsH_mC9WhyohZcleHYKzL3XvjI',
    appId: '1:715990496723:ios:7ec0534f55e3df4486eb26',
    messagingSenderId: '715990496723',
    projectId: 'tonefix-app',
    storageBucket: 'tonefix-app.firebasestorage.app',
    iosBundleId: 'com.example.tonefix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJJz44-o6_cMtmc2WHlX5bkWxCYfrmOgE',
    appId: '1:715990496723:web:3bd537d1f6356cd086eb26',
    messagingSenderId: '715990496723',
    projectId: 'tonefix-app',
    authDomain: 'tonefix-app.firebaseapp.com',
    storageBucket: 'tonefix-app.firebasestorage.app',
    measurementId: 'G-MXMK460WNF',
  );
}
